"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Download, LoaderCircle, Pencil, Plus, Trash2, X } from "lucide-react";
import { jakartaOperationalDate } from "@/lib/dates/jakarta-date";
import { downloadFile } from "@/lib/files/download-file";
import { AppCard, FilterCard, MetricCard, ModalCard, PageHeader, SectionCard, TableCard, nextgenButtonClass, nextgenControlClass, nextgenNeutralButtonClass } from "@/components/ui";
import { ProfitLossChart } from "./profit-loss-chart";

type Transaction = { id: string; date: string; direction: "INCOME" | "EXPENSE"; category: string; description: string; amount: string; source: "JFS" | "NEXTGEN_SYSTEM" | "MANUAL" | "ADJUSTMENT"; sourceReference: string | null; isEditable: boolean };
type Result = { period: { startDate: string; endDate: string }; outletCode: string; summary: Record<string, string>; daily: Array<{ date: string; totalIncome: string; totalExpense: string; profitLoss: string }>; sourceSummary: Array<{ source: string; income: string; expense: string; difference: string }>; categories: string[]; transactions: Transaction[]; pagination: { page: number; pageSize: number; total: number; totalPages: number }; anomalies: string[] };
const money = (value: string | number) => new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(Number(value));
const today = jakartaOperationalDate();
const monthRange = (date: string) => {
  const [year, month] = date.slice(0, 7).split("-").map(Number);
  return { start: `${year}-${String(month).padStart(2, "0")}-01`, end: new Date(Date.UTC(year, month, 0)).toISOString().slice(0, 10) };
};
const shiftMonth = (date: string, offset: number) => {
  const current = new Date(`${date.slice(0, 7)}-01T00:00:00.000Z`);
  current.setUTCMonth(current.getUTCMonth() + offset);
  return monthRange(current.toISOString().slice(0, 10));
};
type EntryForm = { date: string; direction: "INCOME" | "EXPENSE"; category: string; description: string; amount: string; reference: string; reason: string };
const emptyForm: EntryForm = { date: today, direction: "INCOME", category: "", description: "", amount: "", reference: "", reason: "" };

export function ProfitLossClient({ canExport, canManage }: { canExport: boolean; canManage: boolean }) {
  const initial = monthRange(today);
  const [startDate, setStartDate] = useState(initial.start), [endDate, setEndDate] = useState(initial.end);
  const [search, setSearch] = useState(""), [direction, setDirection] = useState(""), [source, setSource] = useState(""), [category, setCategory] = useState("");
  const [sort, setSort] = useState("newest"), [page, setPage] = useState(1);
  const [result, setResult] = useState<Result | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const [modal, setModal] = useState<null | { kind: "manual" | "adjustment"; row?: Transaction }>(null);
  const [voiding, setVoiding] = useState<Transaction | null>(null), [form, setForm] = useState(emptyForm), [saving, setSaving] = useState(false), [exporting, setExporting] = useState(false);
  const query = useMemo(() => new URLSearchParams({ startDate, endDate, search, sort, page: String(page), pageSize: "25", ...(direction ? { direction } : {}), ...(source ? { source } : {}), ...(category ? { category } : {}) }), [startDate, endDate, search, sort, page, direction, source, category]);
  const load = useCallback(async () => {
    setLoading(true); setError("");
    try { const response = await fetch(`/api/finance/profit-loss?${query}`, { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.code || "Data Profit Loss gagal dimuat."); setResult(body.data); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Data Profit Loss gagal dimuat."); }
    finally { setLoading(false); }
  }, [query]);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  const setMonth = (range: { start: string; end: string }) => { setStartDate(range.start); setEndDate(range.end); setPage(1); };
  const openCreate = (kind: "manual" | "adjustment", directionValue: "INCOME" | "EXPENSE") => { setForm({ ...emptyForm, direction: directionValue }); setModal({ kind }); };
  const openEdit = (row: Transaction) => { setForm({ date: row.date, direction: row.direction, category: row.category, description: row.description, amount: row.amount, reference: row.sourceReference ?? "", reason: row.source === "ADJUSTMENT" ? row.sourceReference ?? "" : "" }); setModal({ kind: row.source === "ADJUSTMENT" ? "adjustment" : "manual", row }); };
  async function save() {
    if (!modal || saving) return; setSaving(true); setError("");
    try { const base = `/api/finance/profit-loss/${modal.kind === "manual" ? "manual" : "adjustments"}`; const response = await fetch(modal.row ? `${base}/${modal.row.id}` : base, { method: modal.row ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...form, amount: Number(form.amount) }) }); if (!response.ok) throw new Error("Data gagal disimpan."); setModal(null); await load(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Data gagal disimpan."); }
    finally { setSaving(false); }
  }
  async function voidRow() {
    if (!voiding || saving || form.reason.trim().length < 3) return; setSaving(true);
    try { const segment = voiding.source === "ADJUSTMENT" ? "adjustments" : "manual"; const response = await fetch(`/api/finance/profit-loss/${segment}/${voiding.id}`, { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ reason: form.reason }) }); if (!response.ok) throw new Error("Data gagal dihapus."); setVoiding(null); await load(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Data gagal dihapus."); }
    finally { setSaving(false); }
  }
  async function exportExcel() { if (exporting) return; setExporting(true); try { await downloadFile(`/api/finance/profit-loss/export?${query}`); } catch { setError("Export gagal. Silakan coba kembali."); } finally { setExporting(false); } }
  const s = result?.summary;
  return <div className="space-y-6">
    <PageHeader eyebrow="Finance & HR" title="Profit Loss" description="Analisis pemasukan, pengeluaran, serta laba/rugi operasional berdasarkan periode." actions={canExport ? <button onClick={() => void exportExcel()} disabled={exporting} className={nextgenNeutralButtonClass}>{exporting ? <LoaderCircle className="animate-spin" size={16}/> : <Download size={16}/>} {exporting ? "Mengekspor..." : "Export Excel"}</button> : undefined}/>
    {error && <div role="alert" className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-rose-800">{error}</div>}
    <FilterCard><div className="grid gap-3 lg:grid-cols-6"><button className={nextgenNeutralButtonClass} onClick={() => setMonth(shiftMonth(startDate, -1))}>Bulan Sebelumnya</button><button className={nextgenNeutralButtonClass} onClick={() => setMonth(monthRange(today))}>Bulan Ini</button><button className={nextgenNeutralButtonClass} onClick={() => setMonth(shiftMonth(startDate, 1))}>Bulan Berikutnya</button><input aria-label="Tanggal Awal" type="date" value={startDate} onChange={(e) => { setStartDate(e.target.value); setPage(1); }} className={nextgenControlClass}/><input aria-label="Tanggal Akhir" type="date" value={endDate} onChange={(e) => { setEndDate(e.target.value); setPage(1); }} className={nextgenControlClass}/><button onClick={() => void load()} className={nextgenButtonClass}>Refresh</button></div></FilterCard>
    {loading && !result ? <div className="grid min-h-64 place-items-center"><LoaderCircle className="animate-spin text-blue-700"/></div> : result && <>
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><MetricCard label="Total Pemasukan" value={money(s!.totalIncome)}/><MetricCard label="Total Pengeluaran" value={money(s!.totalExpense)}/><MetricCard label={Number(s!.profitLoss) >= 0 ? "Profit" : "Loss"} value={money(s!.profitLoss)}/><MetricCard label="Margin Profit" value={`${s!.margin}%`}/><MetricCard label="Pemasukan JFS" value={money(s!.jfsIncome)}/><MetricCard label="Omzet Pickup DFOD & Tunai" value={money(Number(s!.pickupDfod) + Number(s!.pickupCash))}/><MetricCard label="Pengeluaran JFS" value={money(s!.jfsExpense)}/><MetricCard label="Total Operasional" value={money(s!.operational)}/><MetricCard label="Salary Setelah Kasbon" value={money(s!.salaryNet)}/><MetricCard label="Manual/Adjustment" value={money(s!.manualAdjustment)}/></div>
      <SectionCard title="Profit / Loss Harian"><ProfitLossChart rows={result.daily}/></SectionCard>
      <SectionCard title="Ringkasan Berdasarkan Source"><div className="grid gap-3 md:grid-cols-4">{result.sourceSummary.map((row) => <AppCard key={row.source} className="p-4"><p className="font-bold">{row.source.replace("_", " ")}</p><p className="mt-2 text-sm">Pemasukan: {money(row.income)}</p><p className="text-sm">Pengeluaran: {money(row.expense)}</p><p className="mt-1 font-semibold">Selisih: {money(row.difference)}</p></AppCard>)}</div><p className="mt-3 text-xs text-slate-500">{result.anomalies[0]}</p></SectionCard>
      <SectionCard title="Rincian Transaksi"><div className="mb-4 flex flex-wrap gap-2">{canManage && <><button className={nextgenButtonClass} onClick={() => openCreate("manual", "INCOME")}><Plus size={16}/>Tambah Pemasukan</button><button className={nextgenButtonClass} onClick={() => openCreate("manual", "EXPENSE")}><Plus size={16}/>Tambah Pengeluaran</button><button className={nextgenNeutralButtonClass} onClick={() => openCreate("adjustment", "INCOME")}><Plus size={16}/>Adjustment</button></>}</div><div className="mb-4 grid gap-2 md:grid-cols-5"><input placeholder="Cari" value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} className={nextgenControlClass}/><select value={direction} onChange={(e) => { setDirection(e.target.value); setPage(1); }} className={nextgenControlClass}><option value="">Semua Jenis</option><option value="INCOME">Pemasukan</option><option value="EXPENSE">Pengeluaran</option></select><select value={source} onChange={(e) => { setSource(e.target.value); setPage(1); }} className={nextgenControlClass}><option value="">Semua Source</option>{["JFS", "NEXTGEN_SYSTEM", "MANUAL", "ADJUSTMENT"].map((v) => <option key={v}>{v}</option>)}</select><select value={category} onChange={(e) => { setCategory(e.target.value); setPage(1); }} className={nextgenControlClass}><option value="">Semua Kategori</option>{result.categories.map((v) => <option key={v}>{v}</option>)}</select><select value={sort} onChange={(e) => setSort(e.target.value)} className={nextgenControlClass}><option value="newest">Terbaru</option><option value="oldest">Terlama</option></select></div>
      <TableCard><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr>{["Tanggal", "Jenis", "Keterangan", "Nominal", "Source", "Aksi"].map((v) => <th key={v} className="px-4 py-3">{v}</th>)}</tr></thead><tbody className="divide-y">{result.transactions.map((row) => <tr key={`${row.source}:${row.id}`}><td className="px-4 py-3">{row.date}</td><td className="px-4 py-3">{row.direction === "INCOME" ? "Pemasukan" : "Pengeluaran"}</td><td className="px-4 py-3"><strong>{row.description}</strong><br/><span className="text-xs text-slate-500">{row.category}</span></td><td className="px-4 py-3 font-semibold">{money(row.amount)}</td><td className="px-4 py-3">{row.source.replace("_", " ")}</td><td className="px-4 py-3">{row.isEditable && canManage ? <div className="flex gap-2"><button aria-label="Edit" onClick={() => openEdit(row)}><Pencil size={16}/></button><button aria-label="Hapus" onClick={() => { setForm({ ...emptyForm, reason: "" }); setVoiding(row); }} className="text-rose-700"><Trash2 size={16}/></button></div> : "—"}</td></tr>)}</tbody></table></div></TableCard><div className="mt-3 flex justify-between text-sm"><span>{result.pagination.total} transaksi</span><div className="flex gap-2"><button disabled={page <= 1} onClick={() => setPage((v) => v - 1)} className={nextgenNeutralButtonClass}>Sebelumnya</button><button disabled={page >= result.pagination.totalPages} onClick={() => setPage((v) => v + 1)} className={nextgenNeutralButtonClass}>Berikutnya</button></div></div></SectionCard>
    </>}
    {modal && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/55 p-4"><ModalCard className="max-w-xl"><div className="flex justify-between border-b p-5"><h2 className="text-xl font-bold">{modal.kind === "adjustment" ? "Adjustment Profit Loss" : modal.row ? "Edit Data Manual" : "Tambah Data Manual"}</h2><button onClick={() => setModal(null)}><X/></button></div><div className="grid gap-3 p-5"><input type="date" value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} className={nextgenControlClass}/><select value={form.direction} onChange={(e) => setForm({ ...form, direction: e.target.value as "INCOME" | "EXPENSE" })} className={nextgenControlClass}><option value="INCOME">Pemasukan</option><option value="EXPENSE">Pengeluaran</option></select><input placeholder="Kategori" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} className={nextgenControlClass}/><input placeholder="Keterangan" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} className={nextgenControlClass}/><input type="number" min="1" placeholder="Nominal" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} className={nextgenControlClass}/>{modal.kind === "manual" ? <input placeholder="Referensi (opsional)" value={form.reference} onChange={(e) => setForm({ ...form, reference: e.target.value })} className={nextgenControlClass}/> : <textarea placeholder="Alasan adjustment" value={form.reason} onChange={(e) => setForm({ ...form, reason: e.target.value })} className={nextgenControlClass}/>}</div><div className="flex justify-end gap-2 border-t p-4"><button onClick={() => setModal(null)} className={nextgenNeutralButtonClass}>Batal</button><button disabled={saving} onClick={() => void save()} className={nextgenButtonClass}>{saving ? "Menyimpan..." : "Simpan"}</button></div></ModalCard></div>}
    {voiding && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/55 p-4"><ModalCard className="max-w-lg"><div className="border-b p-5"><h2 className="text-xl font-bold">Hapus Data Profit Loss</h2></div><div className="space-y-3 p-5"><p>Data dipertahankan sebagai histori dan akan di-void.</p><textarea placeholder="Alasan" value={form.reason} onChange={(e) => setForm({ ...form, reason: e.target.value })} className={nextgenControlClass}/></div><div className="flex justify-end gap-2 border-t p-4"><button onClick={() => setVoiding(null)} className={nextgenNeutralButtonClass}>Batal</button><button disabled={saving || form.reason.trim().length < 3} onClick={() => void voidRow()} className="rounded-lg bg-rose-600 px-4 py-2 font-semibold text-white">Void</button></div></ModalCard></div>}
  </div>;
}
