"use client";

import { useCallback, useEffect, useState } from "react";
import { buttonClass, inputClass, SettingsCard } from "./settings-shell";
import { SettingsMaintenance, type MaintenanceData } from "./settings-maintenance";
import { SettingsUsers, type SettingsUserRow } from "./settings-users";

type Section = "profile" | "users" | "finance" | "integrations" | "maintenance" | "audit";
type Json = Record<string, unknown>;
export function parseSettingsResponse(text: string): Json | null { if (!text.trim()) return null; try { const value = JSON.parse(text) as unknown; return value !== null && typeof value === "object" && !Array.isArray(value) ? value as Json : null; } catch { return null; } }
async function api(url: string, init?: RequestInit) { const response = await fetch(url, { ...init, headers: { "Content-Type": "application/json", ...init?.headers } }); const text = await response.text(); const body = parseSettingsResponse(text); if (!response.ok || !body) throw new Error(String((body?.error as Json | undefined)?.code ?? "SETTINGS_REQUEST_FAILED")); return body; }

export function SettingsClient({ section }: { section: Section }) {
  const [payload, setPayload] = useState<Json | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const endpoint = section === "profile" ? "/api/settings/business-profile" : section === "users" ? "/api/settings/users" : section === "finance" ? "/api/settings/finance/banks" : section === "integrations" ? "/api/settings/integrations" : section === "maintenance" ? "/api/settings/maintenance/preview" : "/api/settings/audit-logs";
  const reload = useCallback(async () => { setLoading(true); setError(""); try { setPayload(await api(endpoint)); } catch (cause) { setError(cause instanceof Error ? cause.message : "Gagal memuat data."); } finally { setLoading(false); } }, [endpoint]);
  useEffect(() => { queueMicrotask(() => void reload()); }, [reload]);
  if (loading) return <div className="h-40 animate-pulse rounded-2xl bg-slate-200" aria-label="Memuat pengaturan" />;
  if (error) return <SettingsCard title="Data tidak dapat dimuat"><p className="text-sm text-red-700">{error}</p><button className={`${buttonClass} mt-4`} onClick={() => void reload()}>Coba lagi</button></SettingsCard>;
  if (section === "profile") return <Profile data={(payload?.data ?? {}) as ProfileData} reload={reload} />;
  if (section === "users") return <SettingsUsers data={(payload?.data ?? []) as SettingsUserRow[]} outletCode={String((payload?.meta as Json | undefined)?.outletCode ?? "")} reload={reload} />;
  if (section === "finance") return <Finance banks={(payload?.data ?? []) as BankRow[]} />;
  if (section === "integrations") return <Integrations data={(payload?.data ?? {}) as Json} reload={reload} />;
  if (section === "maintenance") return <SettingsMaintenance data={(payload?.data ?? {}) as MaintenanceData} reload={reload} />;
  return <Audit data={(payload?.data ?? []) as AuditRow[]} pagination={(payload?.pagination ?? {}) as Json} />;
}

type ProfileData = { tenant?: { name: string; address: string | null; phone: string | null; email: string | null; timezone: string }; outlet?: { name: string; code: string; address: string | null; phone: string | null; email: string | null; adminWhatsapp: string | null; isActive: boolean } };
function Profile({ data, reload }: { data: ProfileData; reload: () => Promise<void> }) { const [form, setForm] = useState(data); const [saving, setSaving] = useState(false); const set = (group: "tenant" | "outlet", key: string, value: string | boolean) => setForm((old) => ({ ...old, [group]: { ...old[group], [key]: value } })); async function save() { setSaving(true); try { await api("/api/settings/business-profile", { method: "PATCH", body: JSON.stringify(form) }); await reload(); } finally { setSaving(false); } } return <div className="grid gap-5 xl:grid-cols-2"><SettingsCard title="Tenant"><Fields values={form.tenant} onChange={(key, value) => set("tenant", key, value)} fields={["name", "address", "phone", "email", "timezone"]} /></SettingsCard><SettingsCard title="Outlet"><Fields values={form.outlet} onChange={(key, value) => set("outlet", key, value)} fields={["name", "code", "address", "phone", "email", "adminWhatsapp"]} /><label className="mt-4 flex items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(form.outlet?.isActive)} onChange={(event) => set("outlet", "isActive", event.target.checked)} /> Outlet aktif</label></SettingsCard><div className="xl:col-span-2"><button className={buttonClass} disabled={saving} onClick={() => void save()}>{saving ? "Menyimpan..." : "Simpan Profil"}</button></div></div>; }
function Fields({ values, fields, onChange }: { values?: Record<string, unknown>; fields: string[]; onChange: (key: string, value: string) => void }) { return <div className="grid gap-4 sm:grid-cols-2">{fields.map((field) => <label key={field} className="text-sm font-medium capitalize text-slate-700">{field.replace(/([A-Z])/g, " $1")}<input className={`${inputClass} mt-1`} value={String(values?.[field] ?? "")} onChange={(event) => onChange(field, event.target.value)} /></label>)}</div>; }

type BankRow = { id: string; bankName: string; accountNumber: string; accountHolder: string; isActive: boolean; isDefault: boolean; displayOrder: number };
type CategoryRow = { id: string; name: string; type: "INCOME" | "EXPENSE"; isActive: boolean; sortOrder: number };
function Finance({ banks }: { banks: BankRow[] }) { const [categories, setCategories] = useState<CategoryRow[]>([]); const [type, setType] = useState<"INCOME" | "EXPENSE">("INCOME"); const [name, setName] = useState(""); const load = useCallback(async () => { const result = await api("/api/settings/finance/categories"); setCategories(result.data as CategoryRow[]); }, []); useEffect(() => { queueMicrotask(() => void load()); }, [load]); async function add() { await api("/api/settings/finance/categories", { method: "POST", body: JSON.stringify({ name, type, isActive: true, sortOrder: categories.length }) }); setName(""); await load(); } async function toggle(item: CategoryRow) { await api(`/api/settings/finance/categories/${item.id}`, { method: "PATCH", body: JSON.stringify({ name: item.name, type: item.type, isActive: !item.isActive, sortOrder: item.sortOrder }) }); await load(); } return <div className="grid gap-5 xl:grid-cols-2"><SettingsCard title="Rekening Bank"><div className="space-y-3">{banks.length === 0 ? <p className="text-sm text-slate-500">Belum ada rekening outlet.</p> : banks.map((bank) => <div key={bank.id} className="rounded-xl border p-3"><b>{bank.bankName}</b><p className="text-sm text-slate-600">{bank.accountNumber} · {bank.accountHolder}</p><p className="text-xs text-slate-500">{bank.isActive ? "Aktif" : "Nonaktif"}{bank.isDefault ? " · Default" : ""}</p></div>)}</div></SettingsCard><SettingsCard title="Kategori Keuangan"><div className="flex gap-2"><input className={inputClass} value={name} placeholder="Nama kategori" onChange={(e) => setName(e.target.value)}/><select className={inputClass} value={type} onChange={(e) => setType(e.target.value as typeof type)}><option value="INCOME">Pemasukan</option><option value="EXPENSE">Pengeluaran</option></select><button className={buttonClass} disabled={name.trim().length < 2} onClick={() => void add()}>Tambah</button></div><div className="mt-4 space-y-2">{categories.map((item) => <div key={item.id} className="flex items-center justify-between rounded-xl border p-3"><span><b>{item.name}</b><small className="ml-2 text-slate-500">{item.type === "INCOME" ? "Pemasukan" : "Pengeluaran"}</small></span><button className="text-sm text-blue-700" onClick={() => void toggle(item)}>{item.isActive ? "Nonaktifkan" : "Aktifkan"}</button></div>)}</div></SettingsCard></div>; }

function Integrations({ data, reload }: { data: Json; reload: () => Promise<void> }) { const [testing, setTesting] = useState(false); const [result, setResult] = useState<Json | null>(null); async function test() { setTesting(true); try { const response = await api("/api/settings/integrations/test", { method: "POST" }); setResult(response.data as Json); await reload(); } finally { setTesting(false); } } return <SettingsCard title="Status Integrasi"><pre className="overflow-auto rounded-xl bg-slate-950 p-4 text-xs text-slate-100">{JSON.stringify(data, null, 2)}</pre><button className={`${buttonClass} mt-4`} disabled={testing} onClick={() => void test()}>{testing ? "Menguji..." : "Test Connection"}</button>{result && <p className="mt-3 text-sm text-emerald-700">Database: {String(result.database)} · Middleware: {String(result.middleware)}</p>}<p className="mt-4 text-xs text-slate-500">Token, credential, DATABASE_URL, dan encryption key tidak pernah ditampilkan.</p></SettingsCard>; }
type AuditRow = { id: string; createdAt: string; actor: { name: string } | null; outlet: { code: string } | null; entityType: string; action: string; metadata: unknown };
function Audit({ data, pagination }: { data: AuditRow[]; pagination: Json }) { return <SettingsCard title="Audit Log"><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="border-b text-left text-slate-500">{["Waktu", "User", "Modul", "Aktivitas", "Outlet", "Detail aman"].map((item) => <th key={item} className="px-3 py-3">{item}</th>)}</tr></thead><tbody>{data.map((row) => <tr key={row.id} className="border-b align-top"><td className="px-3 py-3">{new Date(row.createdAt).toLocaleString("id-ID")}</td><td className="px-3">{row.actor?.name ?? "Sistem"}</td><td className="px-3">{row.entityType}</td><td className="px-3">{row.action}</td><td className="px-3">{row.outlet?.code ?? "Tenant"}</td><td className="max-w-sm px-3"><code className="text-xs">{JSON.stringify(row.metadata)}</code></td></tr>)}</tbody></table></div><p className="mt-4 text-xs text-slate-500">Total {String(pagination.total ?? data.length)} aktivitas. Audit Log bersifat read-only.</p></SettingsCard>; }
